- name: Variables demo - Inventory
  hosts: web
  tasks:
    - name: Print Inventory variables - Host level
      debug:
        msg: "from_ini_host - {{ from_ini_host }}"

    - name: Print Inventory variables - group level
      debug:
        msg: "from_ini_group - {{ from_ini_group }}"

- name: Variables demo - Play Level
  hosts: web
  vars:
    from_play: 300
  vars_files:
    - demo-vars.yml
  tasks:
    - name: Print variables - Play level
      debug:
        msg: "from_play - {{ from_play }}"
    - name: Print variables - Play level from file
      debug:
        msg: "from_files - {{ from_files }}"

- name: Variables demo - From Role
  hosts: web
  roles:
    - sample

- name: Variables demo - Task Level
  hosts: web
  tasks:
    - name: Print variables - Task level
      debug:
        msg: "from_task - {{ from_task }}"
      vars:
        from_task: 700

- name: Variables demo - From Command line
  hosts: web
  tasks:
    - name: Print variables - Command line vars
      debug:
        msg: "from_cli - {{ from_cli }}"
