- name: Variables demo
  hosts: web
  tasks:
    - name: Print Inventory variables - Host level
      debug:
        msg: "from_ini_host - {{ from_ini_host }}"

    - name: Print Inventory variables - group level
      debug:
        msg: "from_ini_group - {{ from_ini_group }}"

