- name: Variable from Inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Print a Message
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Config file update
      ansible.builtin.copy:
        content: "IP: {{ansible_facts['default_ipv4']['address']}}"
        dest: /tmp/ip

    - name: Config file update - Another way
      ansible.builtin.copy:
        content: "IP: {{ansible_facts.default_ipv4.address}}"
        dest: /tmp/ip
